### PR TITLE
Exercise 1.7 for sofie 

### PR DESCRIPTION
**Pull request by SagevdBrand**
## Adding two personal files
- My cv 
- a short story on my near future goal outside of academics

### CODE REVIEW

**Comment by gerkovink** [comment]
Thanks.

**Comment by gerkovink** [comment]
Nice structure to always have a separate branch for each exercise. Are you going to commit exercise 1.8 also - then I will pull your request when those commits have been pushed. If not, then I'll pull now.

**Comment by SagevdBrand** [comment]
I think it might be easier for you indeed to only have to merge once, so ill do another commit to this one 👍

**Comment by gerkovink** [comment]
Cool

**Comment by SagevdBrand** [comment]
It should be done now! Thanks for today's lecture!

**Pull request merged**
